FROM node:14-alpine

LABEL Maintainer="Firman Abdul Hakim <fimzhakim@gmail.com>" \
      Description="Nodejs Expressjs"

# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install && npm cache clean --force

# Bundle app source
COPY . .

EXPOSE 2000

CMD ["npm", "start"]